### ISSUE TITLE
Links de redes sociales:

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/martadero-mockups#10]
Facebook: https://www.facebook.com/proyectomartadero
Twitter: https://twitter.com/martadero
Youtube: https://www.youtube.com/user/proyectomartadero
Flickr: https://www.flickr.com/photos/martadero/albums
Instagram: https://www.instagram.com/proyecto.martadero/
GNUSocial: http://charlemos.barriohacker.net/group/martadero
Google+: https://plus.google.com/+martadero

Creo que estas son todas las que de momento querremos mostrar. Faltaría un botón de RSS que nos permite elegir a qué RSS queremos suscribirnos.

**Comment by jgenso** [comment]
Puedes hacer un mockup de como te imaginas la(s) pantallas del rss?, voy a trabajar hoy al final del dia en esto y pues lo ideal seria ir cerrando estos tickets hoy

**Comment by danicotillas** [comment]
Ok. ¿Crees que puedas tener avanzado también las pantallas de eventos para mañana antes de que vaya? De esa forma aprovechamos más y no estamos por ejemplo subiendo los archivos, etc...

**Comment by jgenso** [comment]
okas

**Comment by danicotillas** [comment]
Los logos irían en el orden de los links como los puse antes. Ahí falta el de GNUSocial que hay que ponerlo como imagen, no hay código de fontawesome. Además, creo que sería bueno poner una imagen de Barrio Hacker que lleve a la web http://barriohacker.net.

Falta además incluir una mención en el footer tal vez como en Festivales en Red - "Federica es un CMS libre bajo licencia "la que creas pertinente" - luego el loguito de Github que lleve al repositorio para los que entienden".

Creo que lo mejor será hacer un post bueno que explique cómo ha sido hecho el sistema, qué es Federica, qué significa CMS (¿porque es eso o tiene otro nombre este sistema?)...

![footer_icons_social](https://cloud.githubusercontent.com/assets/7635775/11966135/312a7f4c-a8d0-11e5-9c41-ed322e04cb79.jpg)

**Comment by danicotillas** [comment]
Sumo el logo de Barrio Hacker en .png
![barrio_hacker](https://cloud.githubusercontent.com/assets/7635775/11966329/8787ee6e-a8d1-11e5-92df-9184ea7c1ffe.png)

**Comment by jgenso** [comment]
Estara en el sgte deploy, con excepcion del icono de gnusocial, he abierto otro issue para generar un font adecuado
