### ISSUE TITLE
Calendario

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/martadero-mockups#15]
Se ve siempre mal:

![captura de pantalla 2015-12-22 17 39 26](https://cloud.githubusercontent.com/assets/7635775/11966578/09d08830-a8d3-11e5-91fd-5dfdd01760a1.png)

**Comment by jgenso** [comment]
@marcelorodcla puedes revisar esto directamente en el repo de federica(es haciendo login dentro del modulo de blog)
