### ISSUE TITLE
Ancho de la caja de texto backend

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/martadero-mockups#16]
Sería ideal que el ancho de la inclusión de texto:

![captura de pantalla 2015-12-22 17 47 32](https://cloud.githubusercontent.com/assets/7635775/11966770/30ab084e-a8d4-11e5-8150-31e3f50ebc4b.png)

tuviese el mismo tamaño que como se previsualiza posteriormente. Puede parecer una tontería pero nos alivianaría un montón de trabajo de edición:

![captura de pantalla 2015-12-22 17 48 29](https://cloud.githubusercontent.com/assets/7635775/11966785/4cd440a8-a8d4-11e5-8ae9-cc47779bb22c.png)

**Comment by jgenso** [comment]
NO es posible varia de pagina en pagina va  a ser un lio
