### ISSUE TITLE
Grilla eventos en INDEX

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/martadero-mockups#2]
Para mostrar los eventos, por favor seguir este diseño en el que son cuadrados y el más grande será porque se decide en el admin digital seleccionándolo en cada caso.

![grilla_index](https://cloud.githubusercontent.com/assets/7635775/10233700/25e2b9b8-685e-11e5-9737-1af355b3290a.png)

**Comment by marcelorodcla** [comment]
@danicotillas listo favor revisar. Daniel, a ver a la brevedad nos podemos reunir para que entienda bien los efectos de los menus y otros detalles. Por otro lado, necesitamos uniformizar los repositorios, tengo psd en el repo que son distintos a los que me enviaron en imagenes a mi email (de hecho la distribución de este issue no es la misma a las del repo ni a las imagenes que me enviaron al email). Saludos.

**Comment by danicotillas** [comment]
Dime tú cuando puedes y dónde y nos juntamos.
Si vienes al mARTadero siempre es más fácil para que así también estén Pablo y Toño.

**Comment by danicotillas** [comment]
Hey @marcelorodcla , del GitHub desapareció la carpeta de HTML/CSS y el index...sólo veo un archivo "martadero-mockups.iml" que no sé ni cómo abrir.
