### ISSUE TITLE
Página Post

### ISSUE THREAD

**Issue by seventyfive** [hacklabcbba/martadero-mockups#3]
en la imagen se puede ver las indicaciones:
Colores del sitio web en general:

blanco: ffffff
Plomo oscuro: 222222
Anaranjado: ec932c

Font títulos grandes
Helvetica75
H1 = tamaño 18 Pt / Bold / Mayúscula / Interlineado 18 / Tracking 25
color: 222222

Font títulos pequeños 
Helvetica75
H2 = tamaño 12 Pt / Bold / Mayúscula / Interlineado 12 / Tracking 25
color: 222222

Font menús desplegables
Helvetica75
H3 = tamaño 9 Pt / Bold / Mayúscula / Interlineado 14 / Tracking 25
color: 222222

Font botones más info
Helvetica75
H4 = tamaño 12 Pt / Bold / Minúscula / Interlineado 12 / Tracking 25
color: 222222

Font Link anaranjado
Helvetica75
H4 = tamaño 12 Pt / Bold / Minúscula / Interlineado 12 / Tracking 25
/ subrayado
color: ec932c

Font citas
Helvetica75
H4 = tamaño 24 Pt / Bold / Minúscula / Interlineado 24 / Tracking 25
color: 222222

Font párrafo
Myriad Pro
P = tamaño 12 Pt / Regular / Minúscula / Interlineado 14 / Tracking 0
color: 222222

![pagina post](https://cloud.githubusercontent.com/assets/14927829/10381681/a3450e24-6dea-11e5-9aa4-89d36efa617d.jpg)

**Comment by seventyfive** [comment]
esta cosa no me deja subir fontsss, algun correo donde mandarte marcelo?

**Comment by seventyfive** [comment]
![Uploading web explicacion1.jpg…]()
![Uploading web explicacion1.jpg…]()

**Comment by marcelorodcla** [comment]
Hecho. Revisar en post.html
