### ISSUE TITLE
Nuevas Pantallas 

### ISSUE THREAD

**Issue by AVillazon** [hacklabcbba/martadero-mockups#6]
areas-programas-principios
![areas-programas-principios](https://cloud.githubusercontent.com/assets/14927606/11286755/387d75e4-8eed-11e5-9fde-7f22e41d4546.jpg)

blog
![blog](https://cloud.githubusercontent.com/assets/14927606/11286753/387b44ae-8eed-11e5-8fbc-903575499deb.jpg)

contacto
![contacto](https://cloud.githubusercontent.com/assets/14927606/11286752/38725ed4-8eed-11e5-8f2b-64564a429dc2.jpg)

convocatorias
![convocatorias](https://cloud.githubusercontent.com/assets/14927606/11286754/387b4f8a-8eed-11e5-8bbf-cfc615654701.jpg)

espacios
![espacios](https://cloud.githubusercontent.com/assets/14927606/11286756/3880bd12-8eed-11e5-9c47-eb2963bce9a8.jpg)

eventos-vista general
![eventos-vista general](https://cloud.githubusercontent.com/assets/14927606/11286757/38964eb6-8eed-11e5-9a78-4705c56e822f.jpg)

feedback-suscripcion
![feedback-suscripcion](https://cloud.githubusercontent.com/assets/14927606/11286760/38a58700-8eed-11e5-908c-ad959b976ca5.jpg)

media
![media](https://cloud.githubusercontent.com/assets/14927606/11286758/389e7f5a-8eed-11e5-94bd-bde83cb0d577.jpg)

participa
![participa](https://cloud.githubusercontent.com/assets/14927606/11286759/38a31826-8eed-11e5-9cea-79fc30071401.jpg)

post
![post](https://cloud.githubusercontent.com/assets/14927606/11286761/38ae9368-8eed-11e5-95b5-43b6ccbac504.jpg)

registro 1
![registro 1](https://cloud.githubusercontent.com/assets/14927606/11286763/38c048e2-8eed-11e5-9c5e-d65905e0ad8d.jpg)

registro 2
![registro 2](https://cloud.githubusercontent.com/assets/14927606/11286762/38bf320e-8eed-11e5-87da-4c96a0a9816e.jpg)

servicios
![servicios](https://cloud.githubusercontent.com/assets/14927606/11286764/38cac6dc-8eed-11e5-8c64-e7f3120dfafb.jpg)

ver evento-taller
![ver evento-taller](https://cloud.githubusercontent.com/assets/14927606/11286765/38d38bc8-8eed-11e5-8e5b-8bc3f8be136b.jpg)

**Comment by jgenso** [comment]
genial

2015-11-19 18:59 GMT-04:00 AVillazon notifications@github.com:

> areas-programas-principios
> [image: areas-programas-principios]
> https://cloud.githubusercontent.com/assets/14927606/11286755/387d75e4-8eed-11e5-9fde-7f22e41d4546.jpg
> 
> blog
> [image: blog]
> https://cloud.githubusercontent.com/assets/14927606/11286753/387b44ae-8eed-11e5-8fbc-903575499deb.jpg
> 
> contacto
> [image: contacto]
> https://cloud.githubusercontent.com/assets/14927606/11286752/38725ed4-8eed-11e5-8f2b-64564a429dc2.jpg
> 
> convocatorias
> [image: convocatorias]
> https://cloud.githubusercontent.com/assets/14927606/11286754/387b4f8a-8eed-11e5-8bbf-cfc615654701.jpg
> 
> espacios
> [image: espacios]
> https://cloud.githubusercontent.com/assets/14927606/11286756/3880bd12-8eed-11e5-9c47-eb2963bce9a8.jpg
> 
> eventos-vista general
> [image: eventos-vista general]
> https://cloud.githubusercontent.com/assets/14927606/11286757/38964eb6-8eed-11e5-9a78-4705c56e822f.jpg
> 
> feedback-suscripcion
> [image: feedback-suscripcion]
> https://cloud.githubusercontent.com/assets/14927606/11286760/38a58700-8eed-11e5-908c-ad959b976ca5.jpg
> 
> media
> [image: media]
> https://cloud.githubusercontent.com/assets/14927606/11286758/389e7f5a-8eed-11e5-94bd-bde83cb0d577.jpg
> 
> participa
> [image: participa]
> https://cloud.githubusercontent.com/assets/14927606/11286759/38a31826-8eed-11e5-9cea-79fc30071401.jpg
> 
> post
> [image: post]
> https://cloud.githubusercontent.com/assets/14927606/11286761/38ae9368-8eed-11e5-95b5-43b6ccbac504.jpg
> 
> registro 1
> [image: registro 1]
> https://cloud.githubusercontent.com/assets/14927606/11286763/38c048e2-8eed-11e5-9c5e-d65905e0ad8d.jpg
> 
> registro 2
> [image: registro 2]
> https://cloud.githubusercontent.com/assets/14927606/11286762/38bf320e-8eed-11e5-87da-4c96a0a9816e.jpg
> 
> servicios
> [image: servicios]
> https://cloud.githubusercontent.com/assets/14927606/11286764/38cac6dc-8eed-11e5-8c64-e7f3120dfafb.jpg
> 
> ver evento-taller
> [image: ver evento-taller]
> https://cloud.githubusercontent.com/assets/14927606/11286765/38d38bc8-8eed-11e5-8e5b-8bc3f8be136b.jpg
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hacklabcbba/martadero-mockups/issues/6.

## 

*Juan Jose Olivera Rodriguez Genso Iniciativas Web +591.44505438 *

**Comment by marcelorodcla** [comment]
Los maquetados ya están pero falta los texto, por ahora están con textos de prueba. Favor si pueden pasar los mockups  en psd o los textos en word.

**Comment by jgenso** [comment]
Subiste el codigo?, algunos de los textos yo los tengo pues estan en la bd
que estoy migrando

El 22 de noviembre de 2015, 15:40, marcelorodcla notifications@github.com
escribió:

> Los maquetados ya están pero falta los texto, por ahora están con textos
> de prueba. Favor si pueden pasar los mockups en psd o los textos en word.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hacklabcbba/martadero-mockups/issues/6#issuecomment-158792755
> .

## 

*Juan Jose Olivera Rodriguez Genso Iniciativas Web +591.44505438 *
