### ISSUE TITLE
Titulos en backend pegados

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/martadero-mockups#7]
Dentro del backend los títulos de las secciones aparecen pegados al menú blanco.

![captura de pantalla 2015-12-16 17 38 39](https://cloud.githubusercontent.com/assets/7635775/11854764/6bad4ad6-a41c-11e5-9a3c-e9f04384c564.png)

**Comment by jgenso** [comment]
@danicotillas en el siguiente deploy va a estar arreglado revisas si todo ok, lo cierras
