### ISSUE TITLE
Vista de páginas con right sidebar

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/martadero-mockups#9]
Páginas como por ejemplo http://staging.martadero.org/areas y todas las que están configuradas para que sean full-width deberían tener siempre un right sidebar.
Podemos ir con el que se muestra en la imagen siguiente y vemos si cambiamos algo para hacer uno stardard:
![resultados busquetas](https://cloud.githubusercontent.com/assets/7635775/11870853/a2d60842-a4a1-11e5-90a4-d28973f3c721.jpg)

**Comment by jgenso** [comment]
@danicotillas me puedes hacer una lista de las paginas actuales donde esto necesita ser cambiado?

**Comment by danicotillas** [comment]
En detalle de Convocatorias: http://staging.martadero.org/convocatoria/568c2689e4b003d78332192a

En http://staging.martadero.org/areas

En detalle SERVICIOS: http://staging.martadero.org/servicio/5658767a44aeb57d15f8cba8

Habrá que ver cómo aparecen las de ÁREAS, PROGRAMAS, etc...
